include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  exclude:
    # Exclude generated code from the analysis
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/injection.config.dart"
    - "packages/solar_monitor_api/**"
linter:
  rules:
    public_member_api_docs: false
