name: solar_monitor
description: Solar monitor Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  connectivity_plus: ^6.1.1
  equatable: ^2.0.7
  fl_chart: ^0.69.2
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  formz: ^0.8.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.2
  go_router: ^14.6.1
  hydrated_bloc: ^9.1.5
  icons_plus: ^5.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  monitoring_repository:
    path: packages/monitoring_repository
  openapi_generator_annotations: ^6.0.0

  path_provider: ^2.1.5
  persistent_storage:
    path: packages/storage/persistent_storage
  shared_preferences: ^2.3.3
  solar_monitor_api:
    path: packages/solar_monitor_api
  storage:
    path: packages/storage/storage
  time_range_picker: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  openapi_generator: ^6.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
